/* ─────────────────────────────────────────────────────────────
   themes.js — all palette definitions.
   Each theme overrides the --palette-* CSS variables on :root.
   Add new themes here; they appear automatically in /studio.
   ───────────────────────────────────────────────────────────── */

export const THEMES = [
  {
    id: 1,
    name: 'Warm Earth',
    desc: 'The original — navy, forest green, amber gold',
    swatches: ['#0C2C47', '#2D5652', '#E2A54D', '#97D3CD', '#EFEAE6', '#E4F2EA'],
    vars: {
      '--palette-navy': '#0C2C47',
      '--palette-forest': '#2D5652',
      '--palette-amber': '#E2A54D',
      '--palette-aqua': '#97D3CD',
      '--palette-blush': '#EFEAE6',
      '--palette-mint': '#E4F2EA',
      '--palette-surface': '#EFEAE6',
      '--palette-background': '#FFFFFF',
      '--palette-foreground': '#0C2C47',
      '--palette-muted': '#2D5652',
      '--palette-border': '#D8D0C8',
    },
  },
  {
    id: 2,
    name: 'Midnight Fantasy',
    desc: 'Dark midnight navy with golden amber & mauve accents',
    swatches: ['#021334', '#012A61', '#275A91', '#977086', '#FDC787', '#A5C5CC'],
    vars: {
      '--palette-navy': '#021334',
      '--palette-forest': '#275A91',
      '--palette-amber': '#FDC787',
      '--palette-aqua': '#A5C5CC',
      '--palette-blush': '#EBF2F4',
      '--palette-mint': '#E8EDF6',
      '--palette-surface': '#EBF2F4',
      '--palette-background': '#F8FBFC',
      '--palette-foreground': '#021334',
      '--palette-muted': '#275A91',
      '--palette-border': '#C5D8DC',
    },
  },
  {
    id: 3,
    name: 'Slate & Rose',
    desc: 'Modern slate grays with a rose-pink accent',
    swatches: ['#1E293B', '#64748B', '#E11D48', '#FDA4AF', '#FFF1F2', '#F8FAFC'],
    vars: {
      '--palette-navy': '#1E293B',
      '--palette-forest': '#64748B',
      '--palette-amber': '#E11D48',
      '--palette-aqua': '#FDA4AF',
      '--palette-blush': '#FFF1F2',
      '--palette-mint': '#F8FAFC',
      '--palette-surface': '#FFF1F2',
      '--palette-background': '#FFFFFF',
      '--palette-foreground': '#1E293B',
      '--palette-muted': '#64748B',
      '--palette-border': '#E2E8F0',
    },
  },
  {
    id: 4,
    name: 'Ivory Tones',
    desc: 'Clean neutral whites — cream beige, linen & soft sand',
    swatches: ['#1A1A1A', '#4A4A4A', '#C8A96E', '#F5F5DC', '#FAF0E6', '#FFFFFF'],
    vars: {
      '--palette-navy': '#1A1A1A',
      '--palette-forest': '#4A4A4A',
      '--palette-amber': '#C8A96E',
      '--palette-aqua': '#D4C5A9',
      '--palette-blush': '#FAF0E6',
      '--palette-mint': '#FFFFF0',
      '--palette-surface': '#F5F5DC',
      '--palette-background': '#FFFFFF',
      '--palette-foreground': '#1A1A1A',
      '--palette-muted': '#4A4A4A',
      '--palette-border': '#F4F4F4',
    },
  },
  {
    id: 5,
    name: 'Ocean Tide',
    desc: 'Deep ocean blues with coral and teal',
    swatches: ['#0C3A5A', '#1A6B8A', '#FF6B6B', '#40C4D3', '#E8F8FA', '#F0FDFF'],
    vars: {
      '--palette-navy': '#0C3A5A',
      '--palette-forest': '#1A6B8A',
      '--palette-amber': '#FF6B6B',
      '--palette-aqua': '#40C4D3',
      '--palette-blush': '#E8F8FA',
      '--palette-mint': '#F0FDFF',
      '--palette-surface': '#E8F8FA',
      '--palette-background': '#FFFFFF',
      '--palette-foreground': '#0C3A5A',
      '--palette-muted': '#1A6B8A',
      '--palette-border': '#BAE6FD',
    },
  },
  {
    id: 6,
    name: 'Noir Gold',
    desc: 'Deep charcoal with warm gold accents',
    swatches: ['#0A0A0A', '#2A2A2A', '#D4AF37', '#C4963A', '#F5F0E8', '#F0EDE5'],
    vars: {
      '--palette-navy': '#0A0A0A',
      '--palette-forest': '#2A2A2A',
      '--palette-amber': '#D4AF37',
      '--palette-aqua': '#C4963A',
      '--palette-blush': '#F5F0E8',
      '--palette-mint': '#F0EDE5',
      '--palette-surface': '#F5F0E8',
      '--palette-background': '#FFFFFF',
      '--palette-foreground': '#0A0A0A',
      '--palette-muted': '#3A3A3A',
      '--palette-border': '#D4C9B8',
    },
  },
]
